/*

 BACKGROUND_MAP.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 40 x 18
   Tile set      : C:\Users\Karun Kanda\Desktop\Karun's Coding Projects\GameboyC\background.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define bgWidth 40
#define bgHeight 18
#define bgBank 0

extern unsigned char bg[];

/* End of BACKGROUND_MAP.H */
