/*

 SPRITES.C

 Tile Source File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 1

  Palette colors       : None.
  SGB Palette          : None.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

/* Start of tile array. */
unsigned char Person[] =
{
  0x7C,0x7C,0x6C,0x44,0x44,0x54,0x7C,0x7C,
  0x10,0x10,0x38,0x38,0x10,0x10,0x28,0x28,
  0x7E,0x7E,0xBD,0xE7,0xFF,0xE7,0xFF,0x81,
  0xFF,0x81,0xE7,0xFF,0xFF,0x81,0x7E,0x7E
};

/* End of SPRITES.C */
